# -*- coding: utf-8 -*-
# 2 Corinthians 6 — Mak Translation authoring plan.
# Each unit is (english, [source-word indices]); [] = supplied filler.
# The assembler joins each unit's Greek/tags in index order and asserts the
# chapter's Greek multiset equals SBLGNT. See tools/co2_assemble.py.
CH = 6
SECTIONS = [
  { "heading": "Now Is the Day of Salvation", "notes": [], "units": [
      ("As we work together with him,", [0]),
      ("", [1]),
      ("we also", [2]),
      ("appeal", [3]),
      ("to you", [12]),
      ("not", [4]),
      ("to receive", [11]),
      ("the grace", [7, 8]),
      ("of God", [9, 10]),
      ("in vain.", [5, 6]),
      ("For", [14]),
      ("he says,", [13]),
      ('"In a favorable time', [15, 16]),
      ("I listened to you,", [17, 18]),
      ("and", [19]),
      ("in", [20]),
      ("a day", [21]),
      ("of salvation", [22]),
      ("I helped you.\"", [23, 24]),
      ("Look,", [25]),
      ("now", [26]),
      ("is the favorable time;", [27, 28]),
      ("look,", [29]),
      ("now", [30]),
      ("is the day", [31]),
      ("of salvation.", [32]),
  ]},
  { "heading": "Commending Ourselves as Servants of God", "notes": [], "units": [
      ("We put", [36]),
      ("no", [33]),
      ("obstacle", [37]),
      ("in", [34]),
      ("anyone's way,", [35]),
      ("so that", [38]),
      ("no", [39]),
      ("fault may be found with", [40]),
      ("our ministry.", [41, 42]),
      ("Instead,", [43]),
      ("in", [44]),
      ("every way", [45]),
      ("we commend", [46]),
      ("ourselves", [47]),
      ("as", [48]),
      ("servants", [50]),
      ("of God:", [49]),
      ("by", [51]),
      ("great", [53]),
      ("endurance,", [52]),
      ("in", [54]),
      ("afflictions,", [55]),
      ("in", [56]),
      ("hardships,", [57]),
      ("in", [58]),
      ("distresses,", [59]),
      ("in", [60]),
      ("beatings,", [61]),
      ("in", [62]),
      ("imprisonments,", [63]),
      ("in", [64]),
      ("riots,", [65]),
      ("in", [66]),
      ("hard labors,", [67]),
      ("in", [68]),
      ("sleepless nights,", [69]),
      ("in", [70]),
      ("hunger;", [71]),
      ("by", [72]),
      ("purity,", [73]),
      ("by", [74]),
      ("knowledge,", [75]),
      ("by", [76]),
      ("patience,", [77]),
      ("by", [78]),
      ("kindness,", [79]),
      ("by", [80]),
      ("the Holy", [82]),
      ("Spirit,", [81]),
      ("by", [83]),
      ("genuine", [85]),
      ("love,", [84]),
      ("by", [86]),
      ("truthful", [88]),
      ("speech,", [87]),
      ("by", [89]),
      ("the power", [90]),
      ("of God;", [91]),
      ("with", [92]),
      ("the weapons", [93, 94]),
      ("of righteousness", [95, 96]),
      ("for the right hand", [97, 98]),
      ("and", [99]),
      ("for the left;", [100]),
  ]},
  { "heading": "Through Honor and Dishonor", "notes": [], "units": [
      ("through", [101]),
      ("glory", [102]),
      ("and", [103]),
      ("dishonor,", [104]),
      ("through", [105]),
      ("slander", [106]),
      ("and", [107]),
      ("praise.", [108]),
      ("We are treated as", [109]),
      ("impostors,", [110]),
      ("and yet are", [111]),
      ("true;", [112]),
      ("as", [113]),
      ("unknown,", [114]),
      ("and yet", [115]),
      ("well known;", [116]),
      ("as", [117]),
      ("dying,", [118]),
      ("and", [119]),
      ("look —", [120]),
      ("we live;", [121]),
      ("as", [122]),
      ("disciplined,", [123]),
      ("and yet", [124]),
      ("not", [125]),
      ("killed;", [126]),
      ("as", [127]),
      ("sorrowful,", [128]),
      ("yet", [130]),
      ("always", [129]),
      ("rejoicing;", [131]),
      ("as", [132]),
      ("poor,", [133]),
      ("yet", [135]),
      ("making many rich;", [134, 136]),
      ("as", [137]),
      ("having", [139]),
      ("nothing,", [138]),
      ("and yet", [140]),
      ("possessing", [142]),
      ("everything.", [141]),
  ]},
  { "heading": "Open Wide Your Hearts", "notes": [], "units": [
      ("We have spoken freely", [143, 144, 145, 146]),
      ("to", [147]),
      ("you,", [148]),
      ("Corinthians;", [149]),
      ("our heart", [150, 151, 152]),
      ("is wide open.", [153]),
      ("You are", [154]),
      ("not", [155]),
      ("restricted", [156]),
      ("by us,", [157]),
      ("but", [159]),
      ("you are restricted", [158]),
      ("in", [160]),
      ("your own", [163]),
      ("affections.", [161, 162]),
      ("As a fair exchange —", [164, 166, 167]),
      ("", [165]),
      ("I speak", [170]),
      ("as", [168]),
      ("to my children —", [169]),
      ("open wide your hearts,", [171]),
      ("you", [173]),
      ("also.", [172]),
  ]},
  { "heading": "The Temple of the Living God", "notes": [], "units": [
      ("Do not be", [174, 175]),
      ("mismatched, yoked together", [176]),
      ("with unbelievers.", [177]),
      ("For", [179]),
      ("what", [178]),
      ("partnership", [180]),
      ("has righteousness", [181]),
      ("with", [182]),
      ("lawlessness?", [183]),
      ("Or", [184]),
      ("what", [185]),
      ("fellowship", [186]),
      ("has light", [187]),
      ("with", [188]),
      ("darkness?", [189]),
      ("And", [191]),
      ("what", [190]),
      ("harmony", [192]),
      ("has Christ", [193]),
      ("with", [194]),
      ("Belial?", [195]),
      ("Or", [196]),
      ("what", [197]),
      ("portion", [198]),
      ("does a believer share", [199]),
      ("with", [200]),
      ("an unbeliever?", [201]),
      ("And", [203]),
      ("what", [202]),
      ("agreement", [204]),
      ("has the temple", [205]),
      ("of God", [206]),
      ("with", [207]),
      ("idols?", [208]),
      ("For", [210]),
      ("we", [209]),
      ("are", [213]),
      ("the temple", [211]),
      ("of the living God;", [212, 214]),
      ("as", [215]),
      ("God", [217, 218]),
      ("said,", [216]),
      ("", [219]),
      ('"I will dwell', [220]),
      ("in", [221]),
      ("them", [222]),
      ("and", [223]),
      ("walk among them,", [224]),
      ("and", [225]),
      ("I will be", [226]),
      ("their", [227]),
      ("God,", [228]),
      ("and", [229]),
      ("they", [230]),
      ("shall be", [231]),
      ("my", [232]),
      ('people."', [233]),
  ]},
  { "heading": "I Will Be a Father to You", "notes": [], "units": [
      ("Therefore", [234]),
      ('"go out', [235]),
      ("from", [236]),
      ("their", [238]),
      ("midst,", [237]),
      ("and", [239]),
      ("be separate,", [240]),
      ("says", [241]),
      ("the Lord,", [242]),
      ("and", [243]),
      ("touch", [246]),
      ("nothing", [245]),
      ("unclean;", [244]),
      ("then I", [247]),
      ("will welcome", [248]),
      ("you,", [249]),
      ("and", [250]),
      ("I will be", [251]),
      ("a father", [253, 254]),
      ("to you,", [252]),
      ("and", [255]),
      ("you", [256]),
      ("shall be", [257]),
      ("sons", [259, 260]),
      ("and", [261]),
      ("daughters", [262]),
      ("to me,", [258]),
      ("says", [263]),
      ("the Lord", [264]),
      ('Almighty."', [265]),
  ]},
]
