# -*- coding: utf-8 -*-
# 1 Peter 5 — Mak Translation authoring plan.
# Each unit is (english, [source-word indices]); [] = supplied filler.
# The assembler joins each unit's Greek/tags in index order and asserts the
# chapter's Greek multiset equals SBLGNT. See tools/nt_assemble.py.
CH = 5
SECTIONS = [
  { "heading": "Shepherd the Flock of God", "notes": [], "units": [
      # v1
      ("So", [1]),
      ("I appeal to", [4]),
      ("the elders", [0]),
      ("among", [2]),
      ("you", [3]),
      ("as", []),
      ("a fellow elder", [5, 6]),
      ("and", [7]),
      ("a witness", [8]),
      ("of the sufferings", [9, 12]),
      ("of Christ,", [10, 11]),
      ("and", [14]),
      ("a partaker", [13, 19]),
      ("of the glory", [15, 18]),
      ("that is about to", [16]),
      ("be revealed:", [17]),
      # v2
      ("shepherd", [20]),
      ("the flock", [21, 24]),
      ("of God", [25, 26]),
      ("that is", []),
      ("among", [22]),
      ("you,", [23]),
      ("exercising oversight,", [27]),
      ("not", [28]),
      ("under compulsion", [29]),
      ("but", [30]),
      ("willingly,", [31]),
      ("as God would have you;", [32, 33]),
      ("nor for shameful gain", [34, 35]),
      ("but", [36]),
      ("eagerly;", [37]),
      # v3
      ("nor", [38]),
      ("as", [39]),
      ("those who lord it over", [40]),
      ("those in your charge,", [41, 42]),
      ("but", [43]),
      ("being", [45]),
      ("examples", [44]),
      ("to the flock.", [46, 47]),
      # v4
      ("And", [48]),
      ("when", []),
      ("the chief Shepherd", [50, 51]),
      ("appears,", [49]),
      ("you will receive", [52]),
      ("the unfading", [53, 54]),
      ("crown", [57]),
      ("of glory.", [55, 56]),
  ]},
  { "heading": "Humble Yourselves", "notes": [], "units": [
      # v5
      ("Likewise,", [58]),
      ("you who are younger,", [59]),
      ("be subject", [60]),
      ("to the elders.", [61]),
      ("", [63]),
      ("Clothe yourselves,", [67]),
      ("all of you,", [62]),
      ("with humility", [65, 66]),
      ("toward one another,", [64]),
      ("for", [68]),
      ("“God", [69, 70]),
      ("opposes", [72]),
      ("the proud", [71]),
      ("but", [74]),
      ("gives", [75]),
      ("grace", [76]),
      ("to the humble.”", [73]),
      # v6
      ("Humble yourselves,", [77]),
      ("therefore,", [78]),
      ("under", [79]),
      ("the mighty", [80, 81]),
      ("hand", [82]),
      ("of God,", [83, 84]),
      ("so that", [85]),
      ("at the proper time", [88, 89]),
      ("he may exalt", [87]),
      ("you,", [86]),
      # v7
      ("casting", [94]),
      ("all", [90]),
      ("your", [93]),
      ("anxieties", [91, 92]),
      ("on", [95]),
      ("him,", [96]),
      ("because", [97]),
      ("he cares", [98, 99]),
      ("for you.", [100, 101]),
      # v8
      ("Be sober-minded;", [102]),
      ("be watchful.", [103]),
      ("Your", [106]),
      ("adversary", [104, 105]),
      ("the devil", [107]),
      ("prowls around", [111]),
      ("like", [108]),
      ("a roaring", [110]),
      ("lion,", [109]),
      ("seeking", [112]),
      ("someone", [113]),
      ("to devour.", [114]),
      # v9
      ("Resist", [116]),
      ("him,", [115]),
      ("firm", [117]),
      ("in the faith,", [118, 119]),
      ("knowing", [120]),
      ("that", []),
      ("the same kinds", [121, 122]),
      ("of suffering", [123, 124]),
      ("are being experienced", [131]),
      ("by your", [129]),
      ("brotherhood", [125, 130]),
      ("throughout the world.", [126, 127, 128]),
      # v10
      ("And", [133]),
      ("the God", [132, 134]),
      ("of all", [135]),
      ("grace,", [136]),
      ("who has called", [137, 138]),
      ("you", [139]),
      ("to", [140]),
      ("his", [143]),
      ("eternal", [141, 142]),
      ("glory", [144]),
      ("in Christ,", [145, 146]),
      ("after you have suffered", [148]),
      ("a little while,", [147]),
      ("he himself", [149]),
      ("will restore,", [150]),
      ("confirm,", [151]),
      ("strengthen,", [152]),
      ("and", []),
      ("establish", [153]),
      ("you.", []),
      # v11
      ("To him", [154]),
      ("be", []),
      ("the dominion", [155, 156]),
      ("forever", [157, 158, 159]),
      ("and ever.", [160, 161]),
      ("Amen.", [162]),
  ]},
  { "heading": "Final Greetings", "notes": [], "units": [
      # v12
      ("By", [163]),
      ("Silvanus,", [164]),
      ("a faithful", [166, 167]),
      ("brother", [168]),
      ("as", [169]),
      ("I regard him,", [170]),
      ("I have written", [173]),
      ("to you", [165]),
      ("briefly,", [171, 172]),
      ("exhorting", [174]),
      ("and", [175]),
      ("declaring", [176]),
      ("that this", [177]),
      ("is", [178]),
      ("the true grace", [179, 180]),
      ("of God.", [181, 182]),
      ("Stand firm", [185]),
      ("in", [183]),
      ("it.", [184]),
      # v13
      ("She who is", [188]),
      ("in Babylon,", [189, 190]),
      ("chosen together with you,", [191]),
      ("greets", [186]),
      ("you,", [187]),
      ("and", [192]),
      ("so does Mark,", [193]),
      ("my", [196]),
      ("son.", [194, 195]),
      # v14
      ("Greet", [197]),
      ("one another", [198]),
      ("with a kiss", [199, 200]),
      ("of love.", [201]),
      ("Peace", [202]),
      ("to all of you", [203, 204]),
      ("who are", [205]),
      ("in Christ.", [206, 207]),
  ]},
]
