# -*- coding: utf-8 -*-
# 1 Timothy 4 — Mak Translation authoring plan.
# Each unit is (english, [source-word indices]); [] = supplied filler.
# The assembler joins each unit's Greek/tags in index order and asserts the
# chapter's Greek multiset equals SBLGNT. See tools/nt_assemble.py.
CH = 4
SECTIONS = [
  { "heading": "In Later Times Some Will Depart from the Faith", "notes": [], "units": [
      ("Now", [1]),
      ("the Spirit", [0, 2]),
      ("clearly", [3]),
      ("says", [4]),
      ("that", [5]),
      ("in", [6]),
      ("later", [7]),
      ("times", [8]),
      ("some", [10]),
      ("will depart from", [9]),
      ("the faith,", [11, 12]),
      ("devoting themselves", [13]),
      ("to deceitful", [15]),
      ("spirits", [14]),
      ("and", [16]),
      ("teachings", [17]),
      ("of demons,", [18]),
      ("through", [19]),
      ("the hypocrisy", [20]),
      ("of liars", [21]),
      ("seared", [22]),
      ("in their own", [24]),
      ("conscience,", [23, 25]),
      ("who forbid", [26]),
      ("marriage", [27]),
      ("and require abstinence from", [28]),
      ("foods", [29]),
      ("that", [30]),
      ("God", [31, 32]),
      ("created", [33]),
      ("to be", [34]),
      ("received", [35]),
      ("with", [36]),
      ("thanksgiving", [37]),
      ("by those", [38]),
      ("who believe", [39]),
      ("and", [40]),
      ("know", [41]),
      ("the truth.", [42, 43]),
  ]},
  { "heading": "Everything Created by God Is Good", "notes": [], "units": [
      ("For", [44]),
      ("everything", [45]),
      ("created", [46]),
      ("by God", [47]),
      ("is good,", [48]),
      ("and", [49]),
      ("nothing", [50]),
      ("is to be rejected", [51]),
      ("if it is received", [54]),
      ("with", [52]),
      ("thanksgiving,", [53]),
      ("for", [56]),
      ("it is made holy", [55]),
      ("by", [57]),
      ("the word", [58]),
      ("of God", [59]),
      ("and", [60]),
      ("prayer.", [61]),
  ]},
  { "heading": "Train Yourself for Godliness", "notes": [], "units": [
      ("If you put", [63]),
      ("these things", [62]),
      ("before the brothers,", [64, 65]),
      ("you will be", [67]),
      ("a good", [66]),
      ("servant", [68]),
      ("of Christ", [69]),
      ("Jesus,", [70]),
      ("nourished", [71]),
      ("on the words", [72, 73]),
      ("of the faith", [74, 75]),
      ("and", [76]),
      ("of the good", [77, 78]),
      ("teaching", [79]),
      ("that", [80]),
      ("you have followed.", [81]),
      ("But", [83]),
      ("have nothing to do with", [88]),
      ("irreverent", [84]),
      ("and silly", [85, 86]),
      ("myths.", [82, 87]),
      ("Rather", [90]),
      ("train", [89]),
      ("yourself", [91]),
      ("for", [92]),
      ("godliness;", [93]),
      ("for", [95]),
      ("while bodily", [94, 96]),
      ("training", [97]),
      ("is", [100]),
      ("of", [98]),
      ("some value,", [99, 101]),
      ("godliness", [102, 103, 104]),
      ("is", [108]),
      ("of value", [107]),
      ("in every way,", [105, 106]),
      ("as it holds", [110]),
      ("promise", [109]),
      ("of life,", [111]),
      ("both for the present", [112, 113]),
      ("and", [114]),
      ("for the life to come.", [115, 116]),
      ("The saying", [118, 119]),
      ("is trustworthy", [117]),
      ("and", [120]),
      ("deserving", [123]),
      ("of full", [121]),
      ("acceptance.", [122]),
      ("For", [126]),
      ("to this end", [124, 125]),
      ("we labor", [127]),
      ("and suffer reproach,", [128, 129]),
      ("because", [130]),
      ("we have set our hope", [131]),
      ("on", [132]),
      ("the living", [134]),
      ("God,", [133]),
      ("who", [135]),
      ("is", [136]),
      ("the Savior", [137]),
      ("of all", [138]),
      ("people,", [139]),
      ("especially", [140]),
      ("of those who believe.", [141]),
  ]},
  { "heading": "Set the Believers an Example", "notes": [], "units": [
      ("Command", [142]),
      ("and", [144]),
      ("teach", [145]),
      ("these things.", [143]),
      ("Let no one", [146]),
      ("despise you", [150]),
      ("for your", [147]),
      ("youth,", [148, 149]),
      ("but", [151]),
      ("become", [153]),
      ("an example", [152]),
      ("to the believers", [154, 155]),
      ("in speech,", [156, 157]),
      ("in conduct,", [158, 159]),
      ("in love,", [160, 161]),
      ("in faith,", [162, 163]),
      ("in purity.", [164, 165]),
      ("Until", [166]),
      ("I come,", [167]),
      ("devote yourself to", [168]),
      ("the public reading of Scripture,", [169, 170]),
      ("to exhortation,", [171, 172]),
      ("to teaching.", [173, 174]),
      ("Do not", [175]),
      ("neglect", [176]),
      ("the gift", [177, 180]),
      ("that is in you,", [178, 179]),
      ("which was given", [181, 182]),
      ("you", [183]),
      ("through", [184]),
      ("prophecy", [185]),
      ("with", [186]),
      ("the laying on", [187]),
      ("of the hands", [188, 189]),
      ("of the council of elders.", [190, 191]),
      ("Practice", [193]),
      ("these things,", [192]),
      ("immerse yourself", [196]),
      ("in them,", [194, 195]),
      ("so that", [197]),
      ("your", [198]),
      ("progress", [199, 200]),
      ("may be", [202]),
      ("evident", [201]),
      ("to all.", [203]),
      ("Keep a close watch on", [204]),
      ("yourself", [205]),
      ("and", [206]),
      ("on the teaching.", [207, 208]),
      ("Persist", [209]),
      ("in them,", [210]),
      ("for", [212]),
      ("by so doing", [211, 213]),
      ("you will save", [216]),
      ("both", [214]),
      ("yourself", [215]),
      ("and", [217]),
      ("your", [220]),
      ("hearers.", [218, 219]),
  ]},
]
