# -*- coding: utf-8 -*-
# 1 Timothy 2 — Mak Translation authoring plan.
# Each unit is (english, [source-word indices]); [] = supplied filler.
# The assembler joins each unit's Greek/tags in index order and asserts the
# chapter's Greek multiset equals SBLGNT. See tools/nt_assemble.py.
CH = 2
SECTIONS = [
  { "heading": "Pray for All People", "notes": [], "units": [
      ("First of all,", [2, 3]),
      ("then,", [1]),
      ("I urge", [0]),
      ("that petitions,", [5]),
      ("prayers,", [6]),
      ("intercessions,", [7]),
      ("and thanksgivings", [8]),
      ("be made", [4]),
      ("for", [9]),
      ("all", [10]),
      ("people —", [11]),
      ("for", [12]),
      ("kings", [13]),
      ("and", [14]),
      ("all", [15]),
      ("who", [16]),
      ("are", [19]),
      ("in", [17]),
      ("high positions,", [18]),
      ("so that", [20]),
      ("we may lead", [25]),
      ("a peaceful", [21]),
      ("and", [22]),
      ("quiet", [23]),
      ("life,", [24]),
      ("in", [26]),
      ("all", [27]),
      ("godliness", [28]),
      ("and", [29]),
      ("dignity.", [30]),
  ]},
  { "heading": "God Our Savior Wants All to Be Saved", "notes": [], "units": [
      ("This is", [31]),
      ("good", [32]),
      ("and", [33]),
      ("acceptable", [34]),
      ("in the sight of", [35]),
      ("God", [39]),
      ("our", [38]),
      ("Savior,", [36, 37]),
      ("who", [40]),
      ("desires", [43]),
      ("all", [41]),
      ("people", [42]),
      ("to be saved", [44]),
      ("and", [45]),
      ("to come", [49]),
      ("to", [46]),
      ("the knowledge", [47]),
      ("of the truth.", [48]),
      ("For", [51]),
      ("there is one", [50]),
      ("God,", [52]),
      ("and", [54]),
      ("there is one", [53]),
      ("mediator", [55]),
      ("between God", [56]),
      ("and", [57]),
      ("men,", [58]),
      ("the man", [59]),
      ("Christ", [60]),
      ("Jesus,", [61]),
      ("who", [62]),
      ("gave", [63]),
      ("himself", [64]),
      ("as a ransom", [65]),
      ("for", [66]),
      ("all —", [67]),
      ("the testimony", [68, 69]),
      ("given at the proper time.", [70, 71]),
      ("For this", [72, 73]),
      ("I was appointed", [74]),
      ("a herald", [75, 76]),
      ("and", [77]),
      ("an apostle —", [78]),
      ("I am telling", [80]),
      ("the truth,", [79]),
      ("I am not", [81]),
      ("lying —", [82]),
      ("a teacher", [83]),
      ("of the Gentiles", [84]),
      ("in", [85]),
      ("faith", [86]),
      ("and", [87]),
      ("truth.", [88]),
  ]},
  { "heading": "How Men and Women Should Come to God", "notes": [], "units": [
      ("I desire,", [89]),
      ("then,", [90]),
      ("that in", [94]),
      ("every", [95]),
      ("place", [96]),
      ("the men", [92, 93]),
      ("should pray,", [91]),
      ("lifting up", [97]),
      ("holy", [98]),
      ("hands", [99]),
      ("without", [100]),
      ("anger", [101]),
      ("or", [102]),
      ("quarreling.", [103]),
      ("Likewise", [104]),
      ("also", [105]),
      ("the women", [106]),
      ("should adorn", [114]),
      ("themselves", [115]),
      ("in", [107]),
      ("respectable", [109]),
      ("clothing,", [108]),
      ("with", [110]),
      ("modesty", [111]),
      ("and", [112]),
      ("self-control,", [113]),
      ("not", [116]),
      ("with", [117]),
      ("braided hair", [118]),
      ("and", [119]),
      ("gold", [120]),
      ("or", [121]),
      ("pearls", [122]),
      ("or", [123]),
      ("costly", [125]),
      ("clothing,", [124]),
      ("but", [126]),
      ("with what", [127]),
      ("is proper", [128]),
      ("for women", [129]),
      ("who profess", [130]),
      ("godliness —", [131]),
      ("with", [132]),
      ("good", [134]),
      ("works.", [133]),
  ]},
  { "heading": "Learning in Quietness", "notes": [], "units": [
      ("Let a woman", [135]),
      ("learn", [138]),
      ("in", [136]),
      ("quietness,", [137]),
      ("with", [139]),
      ("all", [140]),
      ("submissiveness.", [141]),
      ("I do not", [145]),
      ("permit", [146]),
      ("a woman", [144]),
      ("to teach", [142]),
      ("", [143]),
      ("or", [147]),
      ("to exercise authority", [148]),
      ("over a man;", [149]),
      ("rather,", [150]),
      ("she is to remain", [151]),
      ("in", [152]),
      ("quietness.", [153]),
      ("For", [155]),
      ("Adam", [154]),
      ("was formed", [157]),
      ("first,", [156]),
      ("then", [158]),
      ("Eve;", [159]),
      ("and", [160]),
      ("Adam", [161]),
      ("was not", [162]),
      ("deceived,", [163]),
      ("but", [165]),
      ("the", [164]),
      ("woman", [166]),
      ("was thoroughly deceived", [167]),
      ("and became", [170]),
      ("a transgressor.", [168, 169]),
      ("Yet she will be saved", [171, 172]),
      ("through", [173]),
      ("childbearing —", [174, 175]),
      ("if", [176]),
      ("they continue", [177]),
      ("in", [178]),
      ("faith", [179]),
      ("and", [180]),
      ("love", [181]),
      ("and", [182]),
      ("holiness,", [183]),
      ("with", [184]),
      ("self-control.", [185]),
  ]},
]
