# -*- coding: utf-8 -*-
# 1 Timothy 3 — Mak Translation authoring plan.
# Each unit is (english, [source-word indices]); [] = supplied filler.
# The assembler joins each unit's Greek/tags in index order and asserts the
# chapter's Greek multiset equals SBLGNT. See tools/nt_assemble.py.
CH = 3
SECTIONS = [
  { "heading": "The Overseer Must Be Above Reproach", "notes": [], "units": [
      ("The saying is trustworthy:", [0, 1, 2]),
      ("If", [3]),
      ("anyone", [4]),
      ("aspires to", [6]),
      ("the office of overseer,", [5]),
      ("he desires", [9]),
      ("a noble", [7]),
      ("task.", [8]),
      ("Therefore", [11]),
      ("an overseer", [12, 13]),
      ("must", [10]),
      ("be", [15]),
      ("above reproach,", [14]),
      ("the husband", [18]),
      ("of one", [16]),
      ("wife,", [17]),
      ("sober-minded,", [19]),
      ("self-controlled,", [20]),
      ("respectable,", [21]),
      ("hospitable,", [22]),
      ("able to teach,", [23]),
      ("not", [24]),
      ("a drunkard,", [25]),
      ("not", [26]),
      ("violent", [27]),
      ("but", [28]),
      ("gentle,", [29]),
      ("not quarrelsome,", [30]),
      ("not a lover of money.", [31]),
  ]},
  { "heading": "He Must Manage His Own House Well", "notes": [], "units": [
      ("He must manage", [36]),
      ("his own", [32, 33]),
      ("household", [34]),
      ("well,", [35]),
      ("keeping", [38]),
      ("his children", [37]),
      ("submissive", [39, 40]),
      ("with", [41]),
      ("all", [42]),
      ("dignity —", [43]),
      ("for", [45]),
      ("if", [44]),
      ("anyone", [46]),
      ("does not", [51]),
      ("know", [52]),
      ("how", [53]),
      ("to manage", [50]),
      ("his own", [47, 48]),
      ("household,", [49]),
      ("how will he care for", [56]),
      ("God's", [55]),
      ("church?", [54]),
      ("He must not be", [57]),
      ("a recent convert,", [58]),
      ("or", [59, 60]),
      ("he may become puffed up with conceit", [61]),
      ("and fall", [64]),
      ("into", [62]),
      ("the condemnation", [63]),
      ("of the devil.", [65, 66]),
      ("He must", [67]),
      ("also", [68, 69]),
      ("have", [72]),
      ("a good", [71]),
      ("reputation", [70]),
      ("with those", [73, 74]),
      ("outside,", [75]),
      ("so that", [76]),
      ("he may not", [77]),
      ("fall", [80]),
      ("into", [78]),
      ("disgrace", [79]),
      ("and", [81]),
      ("the snare", [82]),
      ("of the devil.", [83, 84]),
  ]},
  { "heading": "Deacons Likewise, Tested and Blameless", "notes": [], "units": [
      ("Deacons", [85]),
      ("likewise", [86]),
      ("must be dignified,", [87]),
      ("not", [88]),
      ("double-tongued,", [89]),
      ("not", [90]),
      ("addicted to", [93]),
      ("much", [92]),
      ("wine,", [91]),
      ("not", [94]),
      ("greedy for dishonest gain.", [95]),
      ("They must hold", [96]),
      ("the mystery", [97, 98]),
      ("of the faith", [99, 100]),
      ("with a clear", [101, 102]),
      ("conscience.", [103]),
      ("And these too", [104, 105, 106]),
      ("must first", [108]),
      ("be tested,", [107]),
      ("and then", [109]),
      ("let them serve", [110]),
      ("if they prove", [112]),
      ("blameless.", [111]),
      ("Their wives", [113]),
      ("likewise", [114]),
      ("must be dignified,", [115]),
      ("not", [116]),
      ("slanderers,", [117]),
      ("but sober-minded,", [118]),
      ("faithful", [119]),
      ("in", [120]),
      ("all things.", [121]),
      ("Let deacons", [122, 123]),
      ("each be the husband", [126]),
      ("of one", [124]),
      ("wife,", [125]),
      ("managing", [129]),
      ("their children", [127]),
      ("and", [130]),
      ("their own", [131, 132]),
      ("households", [133]),
      ("well.", [128]),
      ("For", [135]),
      ("those who", [134]),
      ("serve", [137]),
      ("well", [136]),
      ("gain", [141]),
      ("for themselves", [139]),
      ("a good", [140]),
      ("standing", [138]),
      ("and", [142]),
      ("great", [143]),
      ("confidence", [144]),
      ("in", [145]),
      ("the faith", [146, 147]),
      ("that is in", [148]),
      ("Christ", [149]),
      ("Jesus.", [150]),
  ]},
  { "heading": "The Great Mystery of Godliness", "notes": [], "units": [
      ("I am writing", [153]),
      ("these things", [151]),
      ("to you,", [152]),
      ("hoping", [154]),
      ("to come", [155]),
      ("to", [156]),
      ("you", [157]),
      ("soon.", [158, 159]),
      ("But", [161]),
      ("if", [160]),
      ("I delay,", [162]),
      ("you may know", [163, 164]),
      ("how", [165]),
      ("one ought", [166]),
      ("to conduct oneself", [170]),
      ("in", [167]),
      ("the household", [168]),
      ("of God,", [169]),
      ("which", [171]),
      ("is", [172]),
      ("the church", [173]),
      ("of the living", [175]),
      ("God,", [174]),
      ("the pillar", [176]),
      ("and", [177]),
      ("foundation", [178]),
      ("of the", [179]),
      ("truth.", [180]),
      ("", [181]),
      ("Great indeed,", [183]),
      ("we confess,", [182]),
      ("is", [184]),
      ("the mystery", [185, 188]),
      ("of godliness:", [186, 187]),
      ("He", [189]),
      ("was manifested", [190]),
      ("in", [191]),
      ("the flesh,", [192]),
      ("vindicated", [193]),
      ("by", [194]),
      ("the Spirit,", [195]),
      ("seen", [196]),
      ("by angels,", [197]),
      ("proclaimed", [198]),
      ("among", [199]),
      ("the nations,", [200]),
      ("believed on", [201]),
      ("in", [202]),
      ("the world,", [203]),
      ("taken up", [204]),
      ("in", [205]),
      ("glory.", [206]),
  ]},
]
