# -*- coding: utf-8 -*-
# 2 Timothy 3 — Mak Translation authoring plan.
# Each unit is (english, [source-word indices]); [] = supplied filler.
# The assembler joins each unit's Greek/tags in index order and asserts the
# chapter's Greek multiset equals SBLGNT. See tools/nt_assemble.py.
CH = 3
SECTIONS = [
  { "heading": "In the Last Days, Difficult Times Will Come", "notes": [], "units": [
      ("But", [1]),
      ("understand", [2]),
      ("this:", [0]),
      ("that", [3]),
      ("in", [4]),
      ("the last", [5]),
      ("days", [6]),
      ("there will come", [7]),
      ("times", [8]),
      ("of difficulty.", [9]),
      ("For", [11]),
      ("people", [12, 13]),
      ("will be", [10]),
      ("lovers of self,", [14]),
      ("lovers of money,", [15]),
      ("boastful,", [16]),
      ("arrogant,", [17]),
      ("abusive,", [18]),
      ("disobedient", [20]),
      ("to their parents,", [19]),
      ("ungrateful,", [21]),
      ("unholy,", [22]),
      ("heartless,", [23]),
      ("unforgiving,", [24]),
      ("slanderous,", [25]),
      ("without self-control,", [26]),
      ("brutal,", [27]),
      ("no lovers of good,", [28]),
      ("treacherous,", [29]),
      ("reckless,", [30]),
      ("swollen with conceit,", [31]),
      ("lovers of pleasure", [32]),
      ("rather", [33]),
      ("than", [34]),
      ("lovers of God —", [35]),
      ("having", [36]),
      ("the appearance", [37]),
      ("of godliness,", [38]),
      ("but denying", [39, 40, 43]),
      ("its", [42]),
      ("power.", [41]),
      ("Avoid", [46]),
      ("such people.", [44, 45]),
  ]},
  { "heading": "Always Learning, Never Coming to the Truth", "notes": [], "units": [
      ("For", [49]),
      ("among such", [47, 48]),
      ("are", [50]),
      ("those", [51]),
      ("who slip", [52]),
      ("into", [53]),
      ("households", [54, 55]),
      ("and", [56]),
      ("capture", [57]),
      ("weak-willed women,", [58]),
      ("burdened", [59]),
      ("with sins", [60]),
      ("and led astray", [61]),
      ("by all kinds", [63]),
      ("of desires,", [62]),
      ("always", [64]),
      ("learning", [65]),
      ("and", [66]),
      ("never", [67]),
      ("able", [72]),
      ("to arrive at", [68, 71]),
      ("a knowledge", [69]),
      ("of the truth.", [70]),
      ("Just as", [73, 74]),
      ("", [75]),
      ("Jannes", [76]),
      ("and", [77]),
      ("Jambres", [78]),
      ("opposed", [79]),
      ("Moses,", [80]),
      ("so", [81]),
      ("these men", [83]),
      ("too", [82]),
      ("oppose", [84]),
      ("the truth —", [85, 86]),
      ("men", [87]),
      ("corrupted", [88]),
      ("in mind,", [89, 90]),
      ("disqualified", [91]),
      ("regarding", [92]),
      ("the faith.", [93, 94]),
      ("But", [95]),
      ("they will not", [96]),
      ("get", [97]),
      ("very far,", [98, 99]),
      ("for", [101]),
      ("their", [103]),
      ("folly", [100, 102]),
      ("will be", [105]),
      ("plain", [104]),
      ("to all,", [106]),
      ("as", [107]),
      ("was", [111]),
      ("also", [108]),
      ("that", [109]),
      ("of those two.", [110]),
  ]},
  { "heading": "But You Have Followed My Teaching", "notes": [], "units": [
      ("You,", [112]),
      ("however,", [113]),
      ("have followed", [114]),
      ("my", [115]),
      ("teaching,", [116, 117]),
      ("my conduct,", [118, 119]),
      ("my purpose in life,", [120, 121]),
      ("my faith,", [122, 123]),
      ("my patience,", [124, 125]),
      ("my love,", [126, 127]),
      ("my steadfastness,", [128, 129]),
      ("my persecutions,", [130, 131]),
      ("my sufferings —", [132, 133]),
      ("what", [134]),
      ("happened", [136]),
      ("to me", [135]),
      ("in", [137]),
      ("Antioch,", [138]),
      ("in", [139]),
      ("Iconium,", [140]),
      ("in", [141]),
      ("Lystra —", [142]),
      ("what", [143]),
      ("persecutions", [144]),
      ("I endured,", [145]),
      ("and", [146]),
      ("out of", [147]),
      ("them all", [148]),
      ("the Lord", [151, 152]),
      ("rescued", [150]),
      ("me.", [149]),
      ("Indeed,", [153]),
      ("", [155]),
      ("all", [154]),
      ("who", [156]),
      ("desire", [157]),
      ("to live", [158]),
      ("a godly life", [159]),
      ("in", [160]),
      ("Christ", [161]),
      ("Jesus", [162]),
      ("will be persecuted,", [163]),
      ("while", [165]),
      ("evil", [164]),
      ("people", [166]),
      ("and", [167]),
      ("impostors", [168]),
      ("will go on", [169]),
      ("from bad to worse,", [170, 171, 172]),
      ("deceiving", [173]),
      ("and", [174]),
      ("being deceived.", [175]),
  ]},
  { "heading": "Continue in What You Have Learned", "notes": [], "units": [
      ("But you,", [176, 177]),
      ("continue", [178]),
      ("in", [179]),
      ("what", [180]),
      ("you have learned", [181]),
      ("and", [182]),
      ("firmly believed,", [183]),
      ("knowing", [184]),
      ("from", [185]),
      ("whom", [186]),
      ("you learned it,", [187]),
      ("and", [188]),
      ("that", [189]),
      ("from", [190]),
      ("childhood", [191]),
      ("you have known", [194]),
      ("the sacred", [192]),
      ("writings,", [193]),
      ("which", [195]),
      ("are able", [196]),
      ("to make you wise", [197, 198]),
      ("for", [199]),
      ("salvation", [200]),
      ("through", [201]),
      ("faith", [202]),
      ("that is", [203]),
      ("in", [204]),
      ("Christ", [205]),
      ("Jesus.", [206]),
  ]},
  { "heading": "All Scripture Is Breathed Out by God", "notes": [], "units": [
      ("All", [207]),
      ("Scripture", [208]),
      ("is breathed out by God", [209]),
      ("and", [210]),
      ("profitable", [211]),
      ("for", [212]),
      ("teaching,", [213]),
      ("for", [214]),
      ("reproof,", [215]),
      ("for", [216]),
      ("correction,", [217]),
      ("and", []),
      ("for", [218]),
      ("training", [219]),
      ("in righteousness,", [220, 221, 222]),
      ("so that", [223]),
      ("the man", [226, 229]),
      ("of God", [227, 228]),
      ("may be", [225]),
      ("complete,", [224]),
      ("equipped", [234]),
      ("for", [230]),
      ("every", [231]),
      ("good", [233]),
      ("work.", [232]),
  ]},
]
