# -*- coding: utf-8 -*-
# Titus 2 — Mak Translation authoring plan.
# Each unit is (english, [source-word indices]); [] = supplied filler.
# The assembler joins each unit's Greek/tags in index order and asserts the
# chapter's Greek multiset equals SBLGNT. See tools/nt_assemble.py.
CH = 2
SECTIONS = [
  { "heading": "Teach Sound Doctrine", "notes": [], "units": [
      ("But as for you,", [0, 1]),
      ("speak", [2]),
      ("what is fitting for", [3, 4]),
      ("sound", [5, 6]),
      ("doctrine.", [7]),
      ("Older men", [8]),
      ("are to be", [10]),
      ("sober-minded,", [9]),
      ("dignified,", [11]),
      ("self-controlled,", [12]),
      ("sound", [13]),
      ("in faith,", [14, 15]),
      ("in love,", [16, 17]),
      ("and in steadfastness.", [18, 19]),
      ("Older women", [20]),
      ("likewise", [21]),
      ("are to be reverent", [24]),
      ("in", [22]),
      ("their behavior,", [23]),
      ("not", [25]),
      ("slanderers,", [26]),
      ("nor", [27]),
      ("slaves", [30]),
      ("to much", [29]),
      ("wine,", [28]),
      ("teachers of what is good,", [31]),
      ("so that", [32]),
      ("they may train", [33]),
      ("the young women", [34, 35]),
      ("to be", [37]),
      ("lovers of their husbands", [36]),
      ("and of their children,", [38]),
      ("self-controlled,", [39]),
      ("pure,", [40]),
      ("working at home,", [41]),
      ("kind,", [42]),
      ("and submissive", [43]),
      ("to their own", [44, 45]),
      ("husbands,", [46]),
      ("so that", [47]),
      ("the word", [49, 50]),
      ("of God", [51, 52]),
      ("may not", [48]),
      ("be reviled.", [53]),
      ("Likewise,", [56]),
      ("urge", [57]),
      ("the younger men", [54, 55]),
      ("to be self-controlled.", [58]),
      ("In all respects", [59, 60]),
      ("show", [62]),
      ("yourself", [61]),
      ("to be a model", [63]),
      ("of good", [64]),
      ("works,", [65]),
      ("and in", [66]),
      ("your teaching", [67, 68]),
      ("integrity,", [69]),
      ("dignity,", [70]),
      ("and sound", [72]),
      ("speech", [71]),
      ("that cannot be condemned,", [73]),
      ("so that", [74]),
      ("an opponent", [75, 76, 77]),
      ("may be put to shame,", [78]),
      ("having", [80]),
      ("nothing", [79]),
      ("evil", [84]),
      ("to say", [81]),
      ("about us.", [82, 83]),
      ("Bondservants", [85]),
      ("are to be submissive", [88]),
      ("to their own", [86]),
      ("masters", [87]),
      ("in everything,", [89, 90]),
      ("to be", [92]),
      ("well-pleasing,", [91]),
      ("not", [93]),
      ("argumentative,", [94]),
      ("not", [95]),
      ("pilfering,", [96]),
      ("but", [97]),
      ("showing", [100]),
      ("all", [98]),
      ("good", [101]),
      ("faith,", [99]),
      ("so that", [102]),
      ("in everything", [111, 112]),
      ("they may adorn", [110]),
      ("the doctrine", [103, 104]),
      ("of God", [105, 106, 109]),
      ("our", [108]),
      ("Savior.", [107]),
  ]},
  { "heading": "The Grace of God Has Appeared", "notes": [], "units": [
      ("For", [114]),
      ("the grace", [115, 116]),
      ("of God", [117, 118]),
      ("has appeared,", [113]),
      ("bringing salvation", [119]),
      ("for all", [120]),
      ("people,", [121]),
      ("training us", [122, 123]),
      ("so that,", [124]),
      ("renouncing", [125]),
      ("ungodliness", [126, 127]),
      ("and", [128]),
      ("worldly", [130]),
      ("passions,", [129, 131]),
      ("we might live", [137]),
      ("self-controlled", [132]),
      ("and", [133]),
      ("upright", [134]),
      ("and godly", [135, 136]),
      ("in", [138]),
      ("the present", [139, 140]),
      ("age,", [141]),
      ("waiting for", [142]),
      ("the blessed", [143, 144]),
      ("hope,", [145]),
      ("and", [146]),
      ("the appearing", [147]),
      ("of the glory", [148, 149]),
      ("of our", [155]),
      ("great", [151]),
      ("God", [150, 152]),
      ("and", [153]),
      ("Savior", [154]),
      ("Jesus", [156]),
      ("Christ,", [157]),
      ("who", [158]),
      ("gave", [159]),
      ("himself", [160]),
      ("for us", [161, 162]),
      ("to", [163]),
      ("redeem", [164]),
      ("us", [165]),
      ("from", [166]),
      ("all", [167]),
      ("lawlessness", [168]),
      ("and", [169]),
      ("to purify", [170]),
      ("for himself", [171]),
      ("a people", [172]),
      ("for his own possession,", [173]),
      ("zealous", [174]),
      ("for good", [175]),
      ("works.", [176]),
  ]},
  { "heading": "Declare These Things with All Authority", "notes": [], "units": [
      ("Declare", [178]),
      ("these things;", [177]),
      ("exhort", [179, 180]),
      ("and rebuke", [181, 182]),
      ("with all", [183, 184]),
      ("authority.", [185]),
      ("Let no one", [186]),
      ("disregard", [188]),
      ("you.", [187]),
  ]},
]
