# -*- coding: utf-8 -*-
# Titus 1 — Mak Translation authoring plan.
# Each unit is (english, [source-word indices]); [] = supplied filler.
# The assembler joins each unit's Greek/tags in index order and asserts the
# chapter's Greek multiset equals SBLGNT. See tools/nt_assemble.py.
CH = 1
SECTIONS = [
  { "heading": "Greeting", "notes": [], "units": [
      ("Paul,", [0]),
      ("a servant", [1]),
      ("of God", [2]),
      ("and", [4]),
      ("an apostle", [3]),
      ("of Jesus", [5]),
      ("Christ,", [6]),
      ("for the sake of", [7]),
      ("the faith", [8]),
      ("of God's", [10]),
      ("elect", [9]),
      ("and", [11]),
      ("their knowledge", [12]),
      ("of the truth", [13]),
      ("that accords with", [14, 15]),
      ("godliness,", [16]),
      ("in the hope", [17, 18]),
      ("of eternal", [20]),
      ("life,", [19]),
      ("which", [21]),
      ("God,", [23, 25]),
      ("who never lies,", [24]),
      ("promised", [22]),
      ("before", [26]),
      ("the ages began,", [27, 28]),
      ("and", [30]),
      ("at his own", [32]),
      ("appointed time", [31]),
      ("revealed", [29]),
      ("his", [35]),
      ("word", [33, 34]),
      ("through", [36]),
      ("the preaching", [37]),
      ("with which", [38]),
      ("I", [40]),
      ("was entrusted,", [39]),
      ("by", [41]),
      ("the command", [42]),
      ("of God", [46]),
      ("our", [45]),
      ("Savior;", [43, 44]),
      ("To Titus,", [47]),
      ("my true", [48]),
      ("child", [49]),
      ("in", [50]),
      ("a common", [51]),
      ("faith:", [52]),
      ("Grace", [53]),
      ("and", [54]),
      ("peace", [55]),
      ("from", [56]),
      ("God", [57]),
      ("the Father", [58]),
      ("and", [59]),
      ("Christ", [60]),
      ("Jesus", [61]),
      ("our", [64]),
      ("Savior.", [62, 63]),
  ]},
  { "heading": "Qualifications for Elders", "notes": [], "units": [
      ("This is why", [65, 66]),
      ("I left", [67]),
      ("you", [68]),
      ("in", [69]),
      ("Crete,", [70]),
      ("so that", [71]),
      ("you might set in order", [74]),
      ("what remained", [72, 73]),
      ("and", [75]),
      ("appoint", [76]),
      ("elders", [79]),
      ("in every", [77]),
      ("town", [78]),
      ("as", [80]),
      ("I", [81]),
      ("directed", [83]),
      ("you:", [82]),
      ("if", [84]),
      ("anyone", [85]),
      ("is", [86]),
      ("above reproach,", [87]),
      ("the husband", [90]),
      ("of one", [88]),
      ("wife,", [89]),
      ("having children", [91, 92]),
      ("who believe", [93]),
      ("and not", [94]),
      ("open to the charge", [95, 96]),
      ("of debauchery", [97]),
      ("or", [98]),
      ("rebellion.", [99]),
      ("For", [101]),
      ("the overseer", [102, 103]),
      ("must", [100]),
      ("be", [105]),
      ("above reproach", [104]),
      ("as", [106]),
      ("God's", [107]),
      ("steward,", [108]),
      ("not", [109]),
      ("arrogant,", [110]),
      ("not", [111]),
      ("quick-tempered,", [112]),
      ("not", [113]),
      ("a drunkard,", [114]),
      ("not", [115]),
      ("violent,", [116]),
      ("not", [117]),
      ("greedy for shameful gain,", [118]),
      ("but rather", [119]),
      ("hospitable,", [120]),
      ("a lover of good,", [121]),
      ("self-controlled,", [122]),
      ("upright,", [123]),
      ("holy,", [124]),
      ("and disciplined,", [125]),
      ("holding firmly to", [126]),
      ("the trustworthy", [131]),
      ("word", [127, 132]),
      ("that accords with", [128]),
      ("the teaching,", [129, 130]),
      ("so that", [133]),
      ("he may be", [135]),
      ("able", [134]),
      ("both", [136]),
      ("to encourage others", [137]),
      ("with", [138]),
      ("sound", [141, 142]),
      ("teaching", [139, 140]),
      ("and", [143]),
      ("to rebuke", [146]),
      ("those who contradict it.", [144, 145]),
  ]},
  { "heading": "Rebuke the False Teachers", "notes": [], "units": [
      ("For", [148]),
      ("there are", [147]),
      ("many", [149]),
      ("who are also", [150]),
      ("rebellious,", [151]),
      ("empty talkers", [152]),
      ("and", [153]),
      ("deceivers,", [154]),
      ("especially", [155]),
      ("those", [156]),
      ("of", [157]),
      ("the circumcision party.", [158, 159]),
      ("They", [160]),
      ("must", [161]),
      ("be silenced,", [162]),
      ("since they", [163]),
      ("are upsetting", [166]),
      ("whole", [164]),
      ("households", [165]),
      ("by teaching", [167]),
      ("what", [168]),
      ("they ought", [170]),
      ("not,", [169]),
      ("all for the sake of", [173]),
      ("shameful", [171]),
      ("gain.", [172]),
      ("One", [175]),
      ("of them,", [176, 177]),
      ("their own", [178, 179]),
      ("prophet,", [180]),
      ("said,", [174]),
      ("“Cretans", [181]),
      ("are always", [182]),
      ("liars,", [183]),
      ("evil", [184]),
      ("beasts,", [185]),
      ("lazy", [187]),
      ("gluttons.”", [186]),
      ("This", [190]),
      ("testimony", [188, 189]),
      ("is", [191]),
      ("true.", [192]),
      ("For this", [193, 194]),
      ("reason", [195]),
      ("rebuke", [196]),
      ("them", [197]),
      ("sharply,", [198]),
      ("so that", [199]),
      ("they may be sound", [200]),
      ("in", [201]),
      ("the faith,", [202, 203]),
      ("not", [204]),
      ("devoting themselves to", [205]),
      ("Jewish", [206]),
      ("myths", [207]),
      ("and", [208]),
      ("the commands", [209]),
      ("of people", [210]),
      ("who turn away from", [211]),
      ("the truth.", [212, 213]),
      ("To the pure,", [216, 217]),
      ("all things", [214]),
      ("are pure,", [215]),
      ("but", [219]),
      ("to the", [218]),
      ("defiled", [220]),
      ("and", [221]),
      ("unbelieving,", [222]),
      ("nothing", [223]),
      ("is pure;", [224]),
      ("rather,", [225]),
      ("both", [228]),
      ("their", [227]),
      ("mind", [229, 230]),
      ("and", [231]),
      ("conscience", [232, 233]),
      ("are defiled.", [226]),
      ("They profess", [235]),
      ("to know", [236]),
      ("God,", [234]),
      ("but", [238]),
      ("by their", [237]),
      ("deeds", [239]),
      ("they deny him,", [240]),
      ("being", [242]),
      ("detestable,", [241]),
      ("and", [243]),
      ("disobedient,", [244]),
      ("and", [245]),
      ("unfit", [250]),
      ("for", [246]),
      ("any", [247]),
      ("good", [249]),
      ("work.", [248]),
  ]},
]
