# -*- coding: utf-8 -*-
# Titus 3 — Mak Translation authoring plan.
# Each unit is (english, [source-word indices]); [] = supplied filler.
# The assembler joins each unit's Greek/tags in index order and asserts the
# chapter's Greek multiset equals SBLGNT. See tools/nt_assemble.py.
CH = 3
SECTIONS = [
  { "heading": "Be Ready for Every Good Work", "notes": [], "units": [
      ("Remind them", [0, 1]),
      ("to submit", [4]),
      ("to rulers", [2]),
      ("and authorities,", [3]),
      ("to be obedient,", [5]),
      ("to be", [11]),
      ("ready", [10]),
      ("for", [6]),
      ("every", [7]),
      ("good", [9]),
      ("work,", [8]),
      ("to speak evil of", [13]),
      ("no one,", [12]),
      ("to be", [15]),
      ("peaceable,", [14]),
      ("gentle,", [16]),
      ("showing", [18]),
      ("perfect", [17]),
      ("courtesy", [19]),
      ("toward", [20]),
      ("all", [21]),
      ("people.", [22]),
      ("For", [24]),
      ("we", [27]),
      ("too", [26]),
      ("were", [23]),
      ("once", [25]),
      ("foolish,", [28]),
      ("disobedient,", [29]),
      ("led astray,", [30]),
      ("slaves", [31]),
      ("to various", [35]),
      ("passions", [32]),
      ("and", [33]),
      ("pleasures,", [34]),
      ("passing our days", [40]),
      ("in", [36]),
      ("malice", [37]),
      ("and", [38]),
      ("envy,", [39]),
      ("hated", [41]),
      ("and hating", [42]),
      ("one another.", [43]),
  ]},
  { "heading": "Saved by Grace", "notes": [], "units": [
      ("But", [45]),
      ("when", [44]),
      ("the", [46]),
      ("goodness", [47]),
      ("and", [48]),
      ("the loving kindness", [49, 50]),
      ("of God", [52, 55]),
      ("our Savior", [53, 54]),
      ("appeared,", [51]),
      ("he saved", [70]),
      ("us,", [71]),
      ("not", [56]),
      ("because of", [57]),
      ("works", [58]),
      ("of righteousness", [59, 60, 61]),
      ("that", [62]),
      ("we", [64]),
      ("had done,", [63]),
      ("but", [65]),
      ("according to", [66]),
      ("his own", [67, 68]),
      ("mercy,", [69]),
      ("by", [72]),
      ("the washing", [73]),
      ("of regeneration", [74]),
      ("and", [75]),
      ("renewal", [76]),
      ("of the Holy Spirit,", [77, 78]),
      ("whom", [79]),
      ("he poured out", [80]),
      ("on", [81]),
      ("us", [82]),
      ("richly", [83]),
      ("through", [84]),
      ("Jesus", [85]),
      ("Christ", [86]),
      ("our Savior,", [87, 88, 89]),
      ("so that", [90]),
      ("being justified", [91]),
      ("by", [92]),
      ("his", [93]),
      ("grace", [94]),
      ("we might become", [96]),
      ("heirs", [95]),
      ("according to", [97]),
      ("the hope", [98]),
      ("of eternal life.", [99, 100]),
  ]},
  { "heading": "Devote Yourself to Good Works", "notes": [], "units": [
      ("Trustworthy", [101]),
      ("is the saying,", [102, 103]),
      ("and", [104]),
      ("concerning these things", [105, 106]),
      ("I want", [107]),
      ("you", [108]),
      ("to insist,", [109]),
      ("so that", [110]),
      ("those", [115]),
      ("who have believed", [116]),
      ("in God", [117]),
      ("may be careful", [111]),
      ("to devote themselves", [114]),
      ("to good", [112]),
      ("works.", [113]),
      ("These things", [118]),
      ("are", [119]),
      ("excellent", [120]),
      ("and", [121]),
      ("profitable", [122]),
      ("for", [123]),
      ("people.", [124]),
      ("But", [126]),
      ("avoid", [135]),
      ("foolish", [125]),
      ("controversies", [127]),
      ("and", [128]),
      ("genealogies", [129]),
      ("and", [130]),
      ("dissensions", [131]),
      ("and", [132]),
      ("quarrels", [133]),
      ("about the law,", [134]),
      ("for", [137]),
      ("they are", [136]),
      ("unprofitable", [138]),
      ("and", [139]),
      ("worthless.", [140]),
      ("As for a person", [142]),
      ("who stirs division,", [141]),
      ("after", [143]),
      ("a first", [144]),
      ("and", [145]),
      ("second", [146]),
      ("warning", [147]),
      ("have nothing more to do with him,", [148]),
      ("knowing", [149]),
      ("that", [150]),
      ("such a person", [152, 153]),
      ("is warped", [151]),
      ("and", [154]),
      ("sins,", [155]),
      ("being", [156]),
      ("self-condemned.", [157]),
  ]},
  { "heading": "Final Instructions and Grace", "notes": [], "units": [
      ("When", [158]),
      ("I send", [159]),
      ("Artemas", [160]),
      ("to", [161]),
      ("you", [162]),
      ("or", [163]),
      ("Tychicus,", [164]),
      ("do your best", [165]),
      ("to come", [166]),
      ("to", [167]),
      ("me", [168]),
      ("at", [169]),
      ("Nicopolis,", [170]),
      ("for", [172]),
      ("there", [171]),
      ("I have decided", [173]),
      ("to spend the winter.", [174]),
      ("Do your best", [180]),
      ("to speed", [181]),
      ("Zenas", [175]),
      ("the lawyer", [176, 177]),
      ("and", [178]),
      ("Apollos", [179]),
      ("on their way,", []),
      ("so that", [182]),
      ("nothing", [183]),
      ("is lacking", [185]),
      ("for them.", [184]),
      ("And", [187]),
      ("let our people", [188, 189, 190]),
      ("learn", [186]),
      ("to devote themselves", [193]),
      ("to good", [191]),
      ("works,", [192]),
      ("to meet", [194]),
      ("urgent", [196]),
      ("needs,", [195, 197]),
      ("so that", [198]),
      ("they may not be", [199, 200]),
      ("unfruitful.", [201]),
      ("All", [207]),
      ("who are with", [204, 205]),
      ("me", [206]),
      ("greet", [202]),
      ("you.", [203]),
      ("Greet", [208]),
      ("those", [209]),
      ("who love", [210]),
      ("us", [211]),
      ("in", [212]),
      ("faith.", [213]),
      ("Grace", [214, 215]),
      ("be with", [216]),
      ("you", [218]),
      ("all.", [217]),
  ]},
]
